PROJECT_PARENT_DIRS[0]="$HOME/code"

export TERM="xterm-256color"

export PATH=$PATH:/usr/lib/ruby/gems/1.8/bin

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

. ~/.bash_vcs.sh
. ~/.bash_aliases.sh
. ~/.project_alias.sh

if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

